name: Clang Builder

on:
  # push:
  #   branches:
  #     - clang/*
  # schedule:
  #   - cron: '15 1 * * *'
  workflow_dispatch:

env:
  GITLAB_NAME: ${{ secrets.GITLAB_NAME }}
  GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GIT_SECRET: ${{ secrets.GITHUB_SECRET }}
  GIT_SECRET_MAIN: ${{ secrets.GITHUB_SECRET_MAIN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    strategy:

      fail-fast: false

      matrix:
        config:
          - jobs: "main"
            type: "clang"
            check_duplicate: "Y"

          - jobs: "info"
            type: "info"
            check_duplicate: "Y"

    name: Clang-${{ matrix.config.jobs }}
    
    runs-on: ubuntu-latest

    container: 
      image: zycromerz/tcdocker:v2

    steps:

      - name: checkout
        if: matrix.config.type == 'clang'
        uses: actions/checkout@v2
        with:
          path: clang-${{ matrix.config.jobs }}

      - name: Build TC
        if: matrix.config.type == 'clang'
        run: |
          cd clang-${{ matrix.config.jobs }}
          export DEBIAN_FRONTEND=noninteractive
          export PATH=/usr/bin/core_perl:$PATH
          bash ci.sh deps
          bash update-clang-version.sh ${{ matrix.config.jobs }}
          bash clang-builder.sh ${{ matrix.config.jobs }} ${{ matrix.config.check_duplicate }}

      - name: Update Info
        if: matrix.config.type == 'info'
        run: |
          git clone https://${GIT_SECRET_MAIN}@github.com/XeroMz69/Bebas.git -b main
          cd Bebas
          echo "$(date +"%Y%m%d")" >> last-build.txt
          git config user.name "XeroMz69"
          git config user.email "adamyd18@gmail.com"
          git add last-build.txt
          git commit -sm "update last-build.txt to $(date +"%Y%m%d")"
          git show
          git push --all origin -f

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          repository: XeroMz69/Clang
          files: |
            ${{ github.workspace }}/out/*
          name: Xero-Clang-20.0.0
          tag_name: Clang-20.0.0
          body: |
            apalah
          make_latest: true
